project:
  type: website

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: resume.html
        text: Resume
      - href: blog.html
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
